markdown:      kramdown
permalink:     pretty
url:           http://localhost:4000
exclude:       ['node_modules', 'templates', '.babelrc', 'bulma-docs.sass', 'docker-compose.yml', 'package.json', 'yarn.lock', 'versions']
